package com.ticksense.core;

public enum FinishReasonType
{
    COMPLETED,
    BOSS_DEAD,
    PLAYER_DEAD,
    TELEPORTED,
    LOGGED_OUT,
    HOPPED_WORLD,
    LEFT_REGION,
    LEFT_INSTANCE,
    INVENTORY_EXHAUSTED,
    BANK_OPENED,
    IDLE_TIMEOUT,
    ACTIVITY_CHANGED,
    ROOM_COMPLETE,
    WAVE_COMPLETE,
    REWARD_RECEIVED,
    CLIENT_SHUTDOWN,
    AMBIGUOUS_CONTEXT_LOST,
    UNKNOWN
}
